version: "3.9"

services:
  db:
    image: postgres:16
    container_name: notes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_api
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: notes-api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/notes_api
      JWT_SECRET_KEY: your-secret-key
    ports:
      - "8000:8000"

volumes:
  postgres_data: